myVillage/map/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

# including map name to use it in templates.
app_name = 'map'

# Sub urls for map app
urlpatterns = [
    # house gallery
    url(r'^gallery/(?P<pk>[0-9]+)/$', views.gallery, name='gallery'),
    # house audio
    url(r'^audio/(?P<pk>[0-9]+)/$', views.audio, name='audio'),
    # house video
    url(r'^video/(?P<pk>[0-9]+)/$', views.video, name='video'),
    # households
    url(r'^households/', views.HouseList, name='households'),
    # wells
    url(r'^wells/', views.WellsList, name='wells'),
    # wellHistory
    url(r'^wellHistory/(?P<pk>[0-9]+)/$', views.wellHistory, name='wellHistory'),
    # farms
    url(r'^farms/', views.FarmsList, name='farms'),
    # farmHistory
    url(r'^farmHistory/(?P<pk>[0-9]+)/$', views.farmHistory, name='farmHistory'),
    # Year wise farmHistory
    url(r'^farmHistoryYear/(?P<pk>[0-9]+)/$', views.farmHistoryYear, name='farmHistoryYear'),
    # village overview
    url(r'^overview/', views.OverViewList, name='overall'),
]

myVillage/myVillage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myVillage.views import HomePage
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views
from blog.views import signUp

# main urls of our website
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),  # admin page
    url(r'^map/', include('map.urls')), # maps app
    url(r'^predict/', include('predict.urls')), # predict app
    url(r'^farmers/', include('farmers.urls')),  # framers app
    url(r'^school/', include('school.urls')),  # school app
    url(r'^soc/', include('social.urls')),  # social app
    url(r'^$', HomePage.as_view(), name="home"),  # Home page
    url(r'social/', include('blog.urls')),
    url(r'^accounts/signup/$', signUp, name='signup'),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)   # including URL's of static files
urlpatterns = format_suffix_patterns(urlpatterns, False, allowed=['json', 'html'])

myVillage/predict/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

# including map name to use it in templates.
app_name = 'predict'

# Sub urls for predict app
urlpatterns = [
    # predicting weather trends
    url(r'^weather/$', views.weather, name='weather'),
    # predicting market prices
    url(r'^market/', views.market, name='market'),
]

myVillage/templates/base.html
<html>
{% load staticfiles %}
{% load static %}
  <head>
    <meta charset="utf-8">
    <title>My Village</title>
    <link rel="shortcut icon" type="image/png" href="
http://megagriculture.gov.in/public/images/Wall/rice1.jpg
"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <!--link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"-->
    <script src="https://www.amcharts.com/lib/3/ammap.js"></script>
    <script src="https://www.amcharts.com/lib/3/maps/js/worldLow.js"></script>
    <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />


    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script src="https://www.amcharts.com/lib/3/serial.js"></script>
    <script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
    <script src="https:////www.amcharts.com/lib/3/plugins/dataloader/dataloader.min.js"></script>
    <script src="https:////www.amcharts.com/lib/3/maps/js/worldLow.js"></script>
    <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />

    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
<script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
						

    {% block link %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/glyphicons.css'%}">
    {# https://www.eduonix.com/blog/web-programming-tutorials/learn-icon-fonts-bootstrap-4/#}
  </head>
  <body style="background-image: url('{% static "/images/background.png" %}')";>
    <div class="setbgcolor">
    
    <nav class="navbar navbar-expand-lg navbar-inverse navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">My Village</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
	<li class="nav-item">
            <a class="nav-link" href="{% url 'map:overall' %}">Village View</a>
        </li>
	<li class="nav-item">
            <a class="nav-link" href="{% url 'map:farms' %}">Farms</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'map:wells' %}">Wells</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'map:households' %}">Households</a>
        </li>
	<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Predict<span class="caret"></span>
          </a>
          <ul class="dropdown-menu backColor">
            <li><a class="dropdown-item" href="{% url 'predict:weather' %}">Weather Trends</a></li>
          </ul>
        </li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'post_list' %}">Public</a>
        </li>
        <div>
        <ul class="navbar-nav ml-auto navbar-right">
        {% if user.is_authenticated %}
        <li>
          <a class='nav-link' href="{% url 'post_new' %}" >New Post</a>
        </li>
        <li>
          <a class='nav-link' href="{% url 'post_draft_list' %}">Drafts</a>
        </li>
        <li>
          <a class='nav-link' href="{% url 'logout' %}" >Log out</a>
        </li>
        <li>
         <a class='nav-link'>Welcome: {{ user.username }}</a>
        </li>
         {% else %}

          <li class="navbar-item mr-auto"><a class='nav-link' href="{% url 'login' %}" ><span class="glyphicon glyphicon-user"></span>Login</a></li>
        {% endif %}
	</ul>
	</div>
      </ul>
      </ul>
    </div>
</nav>
<br>
    <div class="container mycontent">
          {% block content %}
          {% endblock %}
    </div>
    {% block script %}
    {% endblock %}
    <!--script src="map/detail.js" type="text/javascript"></script-->
</div>
<script type="text/javascript" src="{% static 'js/blog.js' %}"></script>
</body>
</html>

myVillage/templates/index.html
{% extends "base.html" %}

{% block content %}
<style>
.carousel-inner > .carousel-item > img {
  width:1080px;
  height:512px;
}
</style>
    <br>
    <br>
    <!--div class="jumbotron">
        <center><h1>Welcome</h1></center>
    </div-->
	<div class="container con">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	<li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
 	<li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img class="d-block img-fluid" src="static/images/pic1.jpg" alt="First">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" src="static/images/pic2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" src="static/images/pic3.jpg" alt="Third slide">
        </div>
	<div class="carousel-item">
          <img class="d-block img-fluid" src="static/images/pic4.jpg" alt="Third slide">
        </div>
	<div class="carousel-item">
          <img class="d-block img-fluid" src="static/images/pic5.jpg" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

</div>
<script>
$('.carousel').carousel({
  interval: 2000
})
</script>
{% endblock %}