myVillage/map/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

# including map name to use it in templates.
app_name = 'map'

# Sub urls for map app
urlpatterns = [
    # house gallery
    url(r'^gallery/(?P<pk>[0-9]+)/$', views.gallery, name='gallery'),
    # house audio
    url(r'^audio/(?P<pk>[0-9]+)/$', views.audio, name='audio'),
    # house video
    url(r'^video/(?P<pk>[0-9]+)/$', views.video, name='video'),
    # households
    url(r'^households/', views.HouseList, name='households'),
    # wells
    url(r'^wells/', views.WellsList, name='wells'),
    # wellHistory
    url(r'^wellHistory/(?P<pk>[0-9]+)/$', views.wellHistory, name='wellHistory'),
    # farms
    url(r'^farms/', views.FarmsList, name='farms'),
    # farmHistory
    url(r'^farmHistory/(?P<pk>[0-9]+)/$', views.farmHistory, name='farmHistory'),
    # Year wise farmHistory
    url(r'^farmHistoryYear/(?P<pk>[0-9]+)/$', views.farmHistoryYear, name='farmHistoryYear'),
    # village overview
    url(r'^overview/', views.OverViewList, name='overall'),
]

myVillage/myVillage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myVillage.views import HomePage
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views
from blog.views import signUp

# main urls of our website
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),  # admin page
    url(r'^map/', include('map.urls')), # maps app
    url(r'^predict/', include('predict.urls')), # predict app
    url(r'^farmers/', include('farmers.urls')),  # framers app
    url(r'^school/', include('school.urls')),  # school app
    url(r'^soc/', include('social.urls')),  # social app
    url(r'^$', HomePage.as_view(), name="home"),  # Home page
    url(r'social/', include('blog.urls')),
    url(r'^accounts/signup/$', signUp, name='signup'),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)   # including URL's of static files
urlpatterns = format_suffix_patterns(urlpatterns, False, allowed=['json', 'html'])

myVillage/map/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

myVillage/map/forms.py
from django import forms

# Creating form for FarmHistory year wise search
class YearForm(forms.Form):
    year = forms.CharField(label = 'year', max_length=4)

myVillage/map/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# including modules
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from . import models
from .forms import YearForm
import json
import urllib2
import datetime
from django.template import loader
from django.http import HttpResponse

# view for house gallery
def gallery(request, pk):
    ''' This view returns the list of photos of the selected house and the house id '''
    url="http://10.0.3.23:2729/housePhoto"
    json_obj=urllib2.urlopen(url)
    photolist = json.load(json_obj)
    photolist1=[]
    # filtering photoList of that house
    for obj in photolist:
        if obj['house'] == int(pk):
            photolist1.append('http://10.0.3.23:2729'+obj['photo'].encode('ascii', 'ignore'))
    return render(request, "map/detail_gallery.html", {'loop_times':range(0, len(photolist1)), 'pk':pk, 'photolist':photolist1 })

# view for house audio
def audio(request, pk):
    ''' This view returns the list of audio clips of the selected house and the house id '''
    url="http://10.0.3.23:2729/houseAudio"
    json_obj=urllib2.urlopen(url)
    audiolist = json.load(json_obj)
    audiolist1=[]
    # filtering audioList of that house
    for obj in audiolist:
        if obj['house'] == int(pk):
            audiolist1.append('http://10.0.3.23:2729'+obj['audio'].encode('ascii', 'ignore'))
    return render(request, "map/detail_audio.html", {'loop_times':range(0, len(audiolist1)), 'pk':pk, 'audiolist':audiolist1 })

# view for house video
def video(request, pk):
    ''' This view returns the list of video clips of the selected house and the house id '''
    return render(request, "map/detail_video.html", {'pk':pk})

# Shows the houses on the map
def HouseList(request):
    ''' returns the house attributes retrieved from REST API '''
    url="http://10.0.3.23:2729/house/"
    json_obj=urllib2.urlopen(url)
    houselist=json.load(json_obj)
    # Initialising lists
    latlon=[]
    idList = []
    members=[]
    income=[]
    # Storing the atributes in the corresponding lists
    for i in houselist:
    	latlon.append(i['lat'])
    	latlon.append(i['lon'])
        latlon.append(int(i['id']))
        idList.append(int(i['id']))
        members.append(i['members'])
        income.append(i['income'])
    # Passing the lists to the template
    context={'houselist':json.dumps(houselist),'latlon':latlon,'idList':idList,'members':members,"income":income}
    return render(request,'map/maps.html',context)

# view for the 3D Visualization of the wells on the map
def WellsList(request):
    ''' returns the well attributes retrieved from REST API '''
    url="http://10.0.3.23:2729/wells/"
    json_obj=urllib2.urlopen(url)
    welllist=json.load(json_obj)
    # Initialising lists
    w=[]
    l=[]
    d=[]
    w=[]
    # Storing the atributes in the corresponding lists
    for i in welllist:
    	l.append(i['lat'])
    	l.append(i['lon'])
        d.append(i['depth'])
        w.append(i['averageWaterYield'])
    # Passing the lists to the template
    context={'welllist':json.dumps(welllist),'latlon':l,'depth':d,'water':w}
    return render(request,'map/map_wells.html',context)

# view for showing the houses on the map
def FarmsList(request):
    ''' returns the well attributes retrieved from REST API '''
    url1="http://10.0.3.23:2729/farm/"
    url2="http://10.0.3.23:2729/point/"
    json_obj1=urllib2.urlopen(url1)
    json_obj2=urllib2.urlopen(url2)
    farmlist=json.load(json_obj1)
    pointlist=json.load(json_obj2)
    # Initialising lists
    l=[]
    j=0
    # Storing the atributes in the corresponding lists
    for i in pointlist:
    	l.append(i['lat'])
    	l.append(i['lon'])
        j=j+2
        if(j==8):
            l.append(i['farm'])
            j=0
    # Retrieving farm json object from the server
    url1="http://10.0.3.23:2729/farm"
    json_obj1=urllib2.urlopen(url1)
    farmList=json.load(json_obj1)
    # Retrieving cropping json object from the server
    url2="http://10.0.3.23:2729/cropping/"
    json_obj2=urllib2.urlopen(url2)
    croppingList=json.load(json_obj2)
    dic={}
    for i in range(len(farmList)):
        dic[i]=[]
    # Calculating the current year and season
    now=datetime.datetime.now()
    year=now.year
    month=now.month
    if month>=7 and month<10:
		season_id = 1   #kharif
    elif month>=10 and month<3:
		season_id = 2 # rabi
    else:
		season_id = 3 # summer
    cropList=[]
    for i in croppingList:
        if i['season'] == season_id and i['year'] == str(year):
            dic[i['farm']-1].append(i['crop'])
            dic[i['farm']-1].append(i['area'])
    # Passing the lists to the template
    context={"farmlist":json.dumps(farmlist),'pointlist':json.dumps(pointlist),'latlon':l,'dic':dic}
    return render(request,'map/map_farms.html',context)

# Not required
def farmHistory(request, pk):
    url="http://10.0.3.23:2729/cropping"
    json_obj=urllib2.urlopen(url)
    farmHistoryList = json.load(json_obj)
    farmList=[]
    now=datetime.datetime.now()
    year = now.year
    for obj in farmHistoryList:
        if obj['farm'] == int(pk):
            if obj['year'] == str(year):
                dic=[]
                dic.append(obj['area'])
                dic.append(obj['crop'])
                dic.append(obj['season'])
                farmList.append(dic)
    context={'farmlist':farmList,'pk':pk}
    # photolist1 = [obj['photo'].encode('ascii', 'ignore') for obj in photolist if(obj['house'] == int(pk))]
    return render(request, "map/farmHistory.html",context)

# view for Visualization of year wise farm history on the map
def farmHistoryYear(request, pk):
    ''' returns the year specific farm attributes attributes retrieved from REST API '''
    url="http://10.0.3.23:2729/cropping"
    json_obj=urllib2.urlopen(url)
    farmHistoryList = json.load(json_obj)
    farmList=[]
    # if - If year is entered (POST)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        empty_form = YearForm()
        form = YearForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            flag=0
            for obj in farmHistoryList:
                if obj['farm'] == int(pk):
                    if obj['year'] == request.POST.get('year'):
                        dic=[]
                        dic.append(obj['area'])
                        dic.append(obj['crop'])
                        dic.append(obj['season'])
                        farmList.append(dic)
                        flag=1
            #process the data in form.cleaned_data as required
            locationGo = "/farmHistory/"
            template = loader.get_template("map/farmHistory.html")
            return HttpResponse(template.render({'farmList':farmList,'form':empty_form,'flag':flag},request))
    # If the year is not entered in the form. It shows the current year analysis.
    else:
            now=datetime.datetime.now()
            year=now.year
            flag=0
            for obj in farmHistoryList:
                if obj['farm'] == int(pk):
                    if obj['year'] == str(year):
                        dic=[]
                        dic.append(obj['area'])
                        dic.append(obj['crop'])
                        dic.append(obj['season'])
                        farmList.append(dic)
                        flag=1
            form = YearForm()
            template = loader.get_template("map/farmHistory.html")
            context = {'form': form,'farmList':farmList,'flag':flag}
    return HttpResponse(template.render(context, request))

# View for showing overview of farms, wells and houses on the map of the village.
def OverViewList(request):
    ''' returns attributes of houses, wells and farms '''
    url="http://10.0.3.23:2729/house/"
    json_obj=urllib2.urlopen(url)
    houselist=json.load(json_obj)
    latlon1=[]
    for i in houselist:
    	latlon1.append(i['lat'])
    	latlon1.append(i['lon'])
        latlon1.append(int(i['id']))

    url="http://10.0.3.23:2729/wells/"
    json_obj=urllib2.urlopen(url)
    welllist=json.load(json_obj)
    l2=[]
    for i in welllist:
    	l2.append(i['lat'])
    	l2.append(i['lon'])

    url1="http://10.0.3.23:2729/farm/"
    url2="http://10.0.3.23:2729/point/"
    json_obj1=urllib2.urlopen(url1)
    json_obj2=urllib2.urlopen(url2)
    farmlist=json.load(json_obj1)
    pointlist=json.load(json_obj2)
    l3=[]
    for i in pointlist:
    	l3.append(i['lat'])
    	l3.append(i['lon'])

    context={'houselist':json.dumps(houselist),'latlon':latlon1, 'welllist':json.dumps(welllist),'latlon2':l2, "farmlist":json.dumps(farmlist),'pointlist':json.dumps(pointlist),'latlon3':l3}
    return render(request,'map/map_overview.html',context)

# Not required
def WellVisualize(request):
    url1="http://10.0.3.23:2729/wells/"
    json_obj1=urllib2.urlopen(url1)
    wellsList=json.load(json_obj1)

    url2="http://10.0.3.23:2729/dateTime/"
    json_obj2=urllib2.urlopen(url2)
    dateTimeList=json.load(json_obj2)

    context = {'wellslist':wellslist, 'dateTimeList':dateTimeList}
    return render(request,'#',context)

def wellHistory(request, pk):
    url1="http://10.0.3.23:2729/dateTime"
    json_obj1=urllib2.urlopen(url1)
    wellsList=json.load(json_obj1)
    recentHistoryList=[]
    cnt=0
    # for i in wellsList[::-1]:
    for i in wellsList:
        if i['well']==pk:
    		if cnt==7:
    			break
    		else:
    			recentHistoryList.append(i['wateryield'])
    			cnt+=1
    context = {'recentHistoryList':recentHistoryList,'pk':pk}
    return render(request,'map/wellHistory.html',context)

# view for Visualization of crop statistics in farms using pie chart
def FarmVisualize(request):
    url1="http://10.0.3.23:2729/farm"
    json_obj1=urllib2.urlopen(url1)
    farmList=json.load(json_obj1)

    url2="http://10.0.3.23:2729/cropping/"
    json_obj2=urllib2.urlopen(url2)

myVillage/map/templates/map/detail_audio.html
{% extends "map/detail_base.html" %}
{% block detail %}
    <br>
    <h1>Audio</h1><br>
    <div class="container">
    <div class="row border">
    <br>
    {% for i in audiolist %}
        <br>
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <div class="card card-danger omg">
                <audio controls="controls">
                    <source src={{ i }} type="audio/mpeg">
                    Your browser does not support the HTML5 audio element.
                </audio>
              {# <img class="card-img-top" src="{% static 'images/farmer2.jpeg' %}" alt="Card image cap">#}
              <div class="card-block">
                <!--h4 class="card-title">Name</h4>
                <p class="card-title">Gender</p>
                <p class="card-title">Age</p-->
                <!--p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p-->
              </div>
            </div>
          </div>
          <div class="col-md-12"></div>
    {% endfor %}
    </div>
    </div>
{% endblock %}

myVillage/map/templates/map/detail_base.html
{% extends "base.html" %}
{% load staticfiles %}
<head>
<link rel="stylesheet" href="{% static 'css/glyphicons.css'%}">

</head>
{% block content %}
    <br>
    <div class="container">
        <div class="card text-center">
          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
              <li class="nav-item">
                <a class="nav-link" id="gallery" href="{% url 'map:gallery' pk=pk %}">Gallery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link audio" href="{% url 'map:audio' pk=pk %}">Audio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link video" href="{% url 'map:video' pk=pk %}">Video</a>
              </li>
            </ul>
          </div>
          <div class="card-block colour">
            {% block detail %}

            {% endblock %}
            <h4 class="card-title"></h4>
            <p class="card-text"></p>
            {# <a href="#" class="btn btn-primary"></a>#}
          </div>
          <br>
      </div>
    </div>
{% endblock %}

myVillage/map/templates/map/detail_gallery.html
{% extends "map/detail_base.html" %}
{% load staticfiles %}
{% block detail %}
<head>
    <link rel="stylesheet" href="{% static 'css/glyphicons.css'%}">
</head>
    <br>
    <h1>Gallery</h1>
    <br>
    <div class="container">
    <div class="row border">
    {% for i in photolist %}
          <div class="col-md-4">
            <div class="card card-danger omg">
              <img class="card-img-top" src={{ i }} alt="Card image cap">
              {# <img class="card-img-top" src="{% static 'images/farmer2.jpeg' %}" alt="Card image cap">#}
              <div class="card-block">
                <!--h4 class="card-title">Name</h4>
                <p class="card-title">Gender</p>
                <p class="card-title">Age</p-->
                <!--p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p-->
              </div>
            </div>
          </div>
    {% endfor %}
    </div>
    </div>
{% endblock %}

myVillage/map/templates/map/detail_video.html
{% extends "map/detail_base.html" %}
{% block detail %}
    <br>
    <h1>Video</h1>
    <div class="container">
    <div class="row border">
        <br>
    {# {% for i in videolist width="420" height="315"%}#}
        <br>
          <div class="col-md-12">
            <div class="card card-danger omg">
                <iframe height="500"
                    src="https://www.youtube.com/embed/Z9P-fU67tik">
                </iframe>
                <!--audio controls="controls">
                    <source src={{ i }} type="audio/mpeg">
                    Your browser does not support the HTML5 audio element.
                </audio-->
            </div>
          </div>
    {# {% endfor %}#}
    </div>
    </div>
{% endblock %}

myVillage/map/templates/map/farmHistory.html
{% extends "base.html" %}
{% load staticfiles %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/maps.css' %}">
{% endblock %}
{% block script %}

<style>
#chartdiv {
	width		: 100%;
	height		: 500px;
	font-size	: 11px;
}
#table{

}
#circle1 {
      width: 30px;
      height: 30px;
      -webkit-border-radius: 25px;
      -moz-border-radius: 25px;
      border-radius: 20px;
      background: #99ccff;
    }
    #circle2 {
      width: 30px;
      height: 30px;
      -webkit-border-radius: 25px;
      -moz-border-radius: 25px;
      border-radius: 20px;
      background: #ffff66;
    }
    #circle3 {
      width: 30px;
      height: 30px;
      -webkit-border-radius: 25px;
      -moz-border-radius: 25px;
      border-radius: 20px;
      background: #a6ff4d;
    }

</style>

<!-- Resources -->


<!-- Chart code -->
<script>

var flag={{flag}};

if (flag == 0){
document.getElementById('chartdiv').innerHTML = "<h1>No Data for this year...</h1>";
document.getElementById('table').innerHTML = "<h1> </h1>";
}
else{

var farmList = {{farmList}};
var dic=[];
for (i=0;i<3;i++){
  dic[i]=[];
}
var total=0;
for (i=0;i<farmList.length;i++){
if(farmList[i][2]==1){

    total = total +farmList[i][0]
}
}
console.log(farmList);
console.log(total);

for (i=0;i<farmList.length;i++){

  if (farmList[i][2]==1){

    if(farmList[i][1]==1)
      dic[0][0] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==2)
        dic[0][1] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==3)
        dic[0][2] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==4)
        dic[0][3] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==5)
        dic[0][4] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==6)
        dic[0][5] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==7)
        dic[0][6] = (farmList[i][0]/total)*100

  }
  else if (farmList[i][2]==2) {
    if(farmList[i][1]==1)
      dic[1][0] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==2)
        dic[1][1] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==3)
        dic[1][2] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==4)
        dic[1][3] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==5)
        dic[1][4] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==6)
        dic[1][5] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==7)
        dic[1][6] = (farmList[i][0]/total)*101
  }
  else {
    if(farmList[i][1]==1)
      dic[2][0] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==2)
        dic[2][1] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==3)
        dic[2][2] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==4)
        dic[2][3] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==5)
        dic[2][4] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==6)
        dic[2][5] = (farmList[i][0]/total)*100
    else if (farmList[i][1]==7)
        dic[2][6] = (farmList[i][0]/total)*100
  }
}
console.log(dic);



var chart = AmCharts.makeChart("chartdiv", {
    "theme": "light",
    "type": "serial",
    "dataProvider": [{
        "crop": "Paddy",
        "kharif": dic[0][0],
        "rabi": dic[1][0],
        "summer": dic[2][0],
    }, {
        "crop": "Corn",
        "kharif":dic [0][1],
        "rabi": dic[1][1],
        "summer": dic[2][1],
    }, {
        "crop": "Wheat",
        "kharif":dic [0][2],
        "rabi": dic[1][2],
        "summer": dic[2][2],
    }, {
        "crop": "Jute",
        "kharif":dic [0][3],
        "rabi": dic[1][3],
        "summer": dic[2][3],
    }, {
        "crop": "Tomato",
        "kharif":dic [0][4],
        "rabi": dic[1][4],
        "summer": dic[2][4],
    }, {
        "crop": "Onion",
        "kharif":dic [0][5],
        "rabi": dic[1][5],
        "summer": dic[2][5],
    },{
        "crop": "Cotton",
        "kharif":dic [0][6],
        "rabi": dic[1][6],
        "summer": dic[2][6],
    }],
    "valueAxes": [{
        "unit": "%",
        "position": "left",
        "title": "% of area cultivated",
    }],
    "startDuration": 1,
    "graphs": [{
        "balloonText": "Percentage of Area cultivated of [[category]]: <b>[[value]]</b>",
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "title": "2004",
        "type": "column",
        "columnWidth":0.6,
        "valueField": "kharif"   //blue
    }, {
        "balloonText": "Percentage of Area cultivated of [[category]]: <b>[[value]]</b>",
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "title": "2005",
        "type": "column",
        "clustered":false,
        "columnWidth":0.2,
        "valueField": "rabi"   //yellow
    },{
        "balloonText": "Percentage of Area cultivated of [[category]]: <b>[[value]]</b>",
        "fillAlphas": 0.8,
        "lineAlpha": 0.3,
        "title": "2006",
        "type": "column",
        "clustered":false,
        "columnWidth":0.4,
        "valueField": "summer"  //green
    }],
    "plotAreaFillAlphas": 0.1,
    "categoryField": "crop",
    "categoryAxis": {
        "gridPosition": "start"
    },
    "export": {
    	"enabled": true
     }

});
}

</script>
{% endblock %}
<!-- HTML -->
{% block content %}



<div id="table">
<table>
<tr>
 <th><div id="circle1"></div></th>
 <th>Kharif</th>
 <th>&nbsp</th>
 <th><div id="circle2"></div></th>
 <th>Rabi</th>
 <th>&nbsp</th>
 <th><div id="circle3"></div></th>
 <th>Summer</th>

 </tr>
 </table>
</div>

<!-- <label>Kharif</label>{# <img src="{% static 'images/blue.png' %}" alt="Card image cap">#} &nbsp
<label>Rabi</label>{# <img src="{% static 'images/yellow.png' %}" alt="Card image cap">#}&nbsp
<label>Summer</label>{# <img src="{% static 'images/green.png' %}" alt="Card image cap">#}
 -->


<div id="chartdiv"></div>

<form action="" method="post">
 Search by year:<br>
 {% csrf_token %}
    {{ form }}
    <input type = "submit" value = "Submit" />
</form>

{% endblock %}

myVillage/map/templates/map/maps.html
{% extends "base.html" %}
{% load staticfiles %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/maps.css' %}">

{% endblock %}
{% block script %}


<script>

var latlong={};
var latlon = {{latlon}}
var idList={{idList}}
var members={{members}}
var income = {{income}}
var houselist=JSON.parse('{{ houselist|safe }}')

j=0;
for (i=0;i<idList.length;i++){
if (i%2==0){
  latlong[i]={"latitude":latlon[j]+(i*0.2),"longitude":latlon[j+1]+(i*0.5)}
  j=j+3;}
else{
  latlong[i]={"latitude":latlon[j]+(i*0.1),"longitude":latlon[j+1]+(i*0.3)}
  j=j+3;}
}

var mapData=[]
for (i=0;i<idList.length;i++){
  if(income[i]<100000){
    mapData[i]={"code":i,"name":"House ID:"+idList[i].toString()+"\n"+"Family Size:"+members[i].toString(),"value":members[i],"color":"#eea638"}
  }
  if(income[i]>=100000 && income[i]<200000){
    mapData[i]={"code":i,"name":"House ID:"+idList[i].toString()+"\n"+"Family Size:"+members[i].toString(),"value":members[i],"color":"#de4c4f"}
  }
  if(income[i]>=200000 && income[i]<300000){
    mapData[i]={"code":i,"name":"House ID:"+idList[i].toString()+"\n"+"Family Size:"+members[i].toString(),"value":members[i],"color":"black"}
  }
  if(income[i]>=300000){
    mapData[i]={"code":i,"name":"House ID:"+idList[i].toString()+"\n"+"Family Size:"+members[i].toString(),"value":members[i],"color":"blue"}
  }
}
// get min and max values
var minBulletSize = 3;
var maxBulletSize = 70;
var min = Infinity;
var max = -Infinity;
for ( var i = 0; i < mapData.length; i++ ) {
  var value = mapData[ i ].value;
  if ( value < min ) {
    min = value;
  }
  if ( value > max ) {
    max = value;
  }
}

// it's better to use circle square to show difference between values, not a radius
var maxSquare = maxBulletSize * maxBulletSize * 2 * Math.PI;
var minSquare = minBulletSize * minBulletSize * 2 * Math.PI;

// create circle for each country
var image = [];
for ( var i = 0; i < mapData.length; i++ ) {
  var dataItem = mapData[ i ];
  var value = dataItem.value;
  // calculate size of a bubble
  var square = ( value - min ) / ( max - min ) * ( maxSquare - minSquare ) + minSquare;
  if ( square < minSquare ) {
    square = minSquare;
  }
  var size = Math.sqrt( square / ( Math.PI * 2 ) );
  var id = dataItem.code;

  image.push( {
    "type": "circle",
"theme": "light",

    "width": size,
    "height": size,
    "color": dataItem.color,
    "longitude": latlong[ id ].longitude,
    "latitude": latlong[ id ].latitude,
    "title": dataItem.name,
    "value": value
  } );
}

// build map
var map = AmCharts.makeChart( "chartdiv", {
  "type": "map",
  "projection": "eckert6",
  "titles": [ {
    "text": "Visualisation of location of houses marked by the markers of sizes proprtional to the corresponding family size.",
    "size": 14
  }, {
    "text": "",
    "size": 11
  } ],
  "areasSettings": {
    //"unlistedAreasColor": "#000000",
    //"unlistedAreasAlpha": 0.1
  },
  "dataProvider": {
    "map": "worldLow",
"zoomLevel":85.5,
"zoomLongitude": 12.80,
 "zoomLatitude": 32.72,
//"latitude":17.727056,
//"longitude":80.805960,
    "images": image
  },
  "export": {
    "enabled": true
  }
} );
</script>

<script>

dataPoints= []
var members = {{members}}
var income = {{income}}
var idList = {{idList}}
for(i=0; i<members.length;i++){
  dataPoints[i]= { x: members[i], y: income[i],z:idList[i] }
}

window.onload = function () {



var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,

	zoomEnabled: true,
	title:{
		text: "Family Size Vs Income Plot"
	},
	axisX: {
		title:"Family Size",
		minimum: 1,
		maximum: 10
	},
	axisY:{
		title: "Income (in Rupees)",
    minimum: 70000,
		maximum: 350000
	},
	data: [{
		type: "scatter",
		toolTipContent: "<b>Family Size: </b>{x}<br/><b>Income: </b>{y}<br><b>House ID: </b>{z}",
    markerSize:15,
    dataPoints:dataPoints

	}]
});
chart.render();

}
</script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>



{% endblock %}
<br>
{% block content %}
<div id="chartdiv"></div>
<br>
<p><b>Radius</b>&nbsp-&nbspindicates the family size of house</p>
<div id="table">
<table>
<tr>
 <th><b>Income of the House&nbsp-&nbsp</b></th>
 <th><div id="circle1"></div></th>
 <th>less than 100000</th>
 <th>&nbsp</th>
 <th>&nbsp</th>
 <th><div id="circle2"></div></th>
 <th>between 100000 and 200000</th>
 <th>&nbsp</th>
 <th>&nbsp</th>
 <th><div id="circle3"></div></th>
 <th>between 200000 and 300000</th>
 <th>&nbsp</th>
 <th>&nbsp</th>
 <th><div id="circle4"></div></th>
 <th>greater than 300000</th>
 </tr>
 </table>
</div>
<br>
<br>

<div id="chartContainer" style="height: 500px; width: 100%;"></div>
{% endblock %}